name: java lab

on: 
  push: 
    branches: ["master"]
  pull_request:
    branches: ["master"]
    
  workflow_dispatch:
    
jobs:
  build:
    name: build app
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with: 
          distribution: 'oracle'
          java-version: '17'
          
      - name: Run java
        run: java Main.java

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: java_lab
          path: Main.class
          retention-days: 5

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: java_lab
